name: ht_headlines_client
description: Abstract client for fetching news headlines from various sources.
publish_to: none
repository: https://github.com/headlines-toolkit/ht-headlines-client
environment:
  sdk: ^3.7.0

dependencies:
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  mocktail: ^1.0.4
  test: ^1.25.15
  very_good_analysis: ^7.0.0
